// ===================================================
// コード道場 — 問題データ
// ===================================================

const TOPICS = [
  { id: 'python',     name: 'Python',     icon: '🐍', desc: '構文・型・組み込み関数' },
  { id: 'javascript', name: 'JavaScript', icon: '🟡', desc: '型・スコープ・非同期' },
  { id: 'html',       name: 'HTML',       icon: '🌐', desc: 'タグ・属性・構造' },
  { id: 'css',        name: 'CSS',        icon: '🎨', desc: 'スタイル・Flex・Grid' },
  { id: 'sql',        name: 'SQL',        icon: '🗃', desc: 'クエリ・結合・集計' },
  { id: 'git',        name: 'Git',        icon: '🌿', desc: 'コマンド・ブランチ' },
];

const QUESTIONS = {

  // ==================== Python ====================
  python: [
    {
      id: 'py_001',
      q: 'リストの要素数を取得する関数は？',
      code: 'items = ["a", "b", "c"]',
      answer: 'len(items)',
      dummies: ['items.length', 'size(items)', 'items.count()'],
      exp: 'len() はリスト・文字列・辞書などの要素数を返す組み込み関数。JavaScript の .length プロパティとは異なり、関数として呼ぶ点に注意。',
    },
    {
      id: 'py_002',
      q: '3.14 のデータ型は？',
      code: 'print(type(3.14))',
      answer: 'float',
      dummies: ['double', 'int', 'decimal'],
      exp: 'Python の小数は float 型。Java などにある double 型は Python には存在しない。type() で確認すると <class \'float\'> と表示される。',
    },
    {
      id: 'py_003',
      q: 'このコードの出力は？',
      code: 'print([x**2 for x in range(3)])',
      answer: '[0, 1, 4]',
      dummies: ['[1, 4, 9]', '[0, 1, 2]', '[0, 2, 4]'],
      exp: 'range(3) は 0, 1, 2 を生成する。0²=0, 1²=1, 2²=4。これはリスト内包表記と言い、for ループを1行で書ける Python の重要な機能。',
    },
    {
      id: 'py_004',
      q: 'キーが存在しないときデフォルト値を返すメソッドは？',
      code: 'd = {"a": 1}\nd.???("b", 0)  # → 0',
      answer: 'get',
      dummies: ['fetch', 'find', 'default'],
      exp: 'd.get(key, default) はキーが存在しなければ default を返す。d["b"] と書くと KeyError が起きる。',
    },
    {
      id: 'py_005',
      q: 'このf文字列の出力は？',
      code: 'name = "世界"\nprint(f"Hello, {name}!")',
      answer: 'Hello, 世界!',
      dummies: ['Hello, {name}!', 'f"Hello, 世界!"', 'Hello, name!'],
      exp: 'f文字列（f-string）は Python 3.6 以降の機能。f"..." の中の {} に変数や式を直接埋め込める。',
    },
    {
      id: 'py_006',
      q: 'リストの逆順コピーを返すスライスは？',
      code: 'items = [1, 2, 3, 4, 5]',
      answer: 'items[::-1]',
      dummies: ['items.reverse()', 'items[-1:]', 'reversed(items)'],
      exp: '[::-1] はステップ -1 で全体をスライスし、逆順の新しいリストを返す。items.reverse() は元を変更（in-place）し、返り値は None。',
    },
    {
      id: 'py_007',
      q: 'def func(*args) の *args が受け取るものは？',
      code: null,
      answer: '可変長の位置引数（タプル）',
      dummies: ['可変長のキーワード引数（辞書）', '任意の1つの引数', '引数を展開して渡す演算子'],
      exp: '*args は任意の数の位置引数をタプルとして受け取る。**kwargs はキーワード引数を辞書で受け取る。',
    },
    {
      id: 'py_008',
      q: 'このコードの出力は？',
      code: 'a = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)',
      answer: '[1, 2, 3, 4]',
      dummies: ['[1, 2, 3]', 'エラーが発生する', '[1, 2, 3, [4]]'],
      exp: 'b = a はリストのコピーではなく、同じオブジェクトへの参照を代入する。b を変更すると a も変わる。コピーするには a[:] か list(a) を使う。',
    },
    {
      id: 'py_009',
      q: 'None との比較に使うべき演算子は？',
      code: 'x = None\nif x ??? None:',
      answer: 'is',
      dummies: ['==', '===', 'equals'],
      exp: 'None との比較には == ではなく is を使うのがPython流。is は同一オブジェクトかを確認する。PEP 8 でも is None が推奨されている。',
    },
    {
      id: 'py_010',
      q: 'このコードの出力は？',
      code: 'print("abc" * 3)',
      answer: 'abcabcabc',
      dummies: ['abc3', 'エラーが発生する', 'abc abc abc'],
      exp: 'Python では文字列に整数を掛けると、その回数分繰り返した文字列が返る。リストでも同様に [0] * 3 → [0, 0, 0] のように使える。',
    },
  ],

  // ==================== JavaScript ====================
  javascript: [
    {
      id: 'js_001',
      q: 'typeof null の結果は？',
      code: 'console.log(typeof null)',
      answer: '"object"',
      dummies: ['"null"', '"undefined"', '"string"'],
      exp: 'typeof null が "object" を返すのはJavaScript初期の有名なバグ。null はオブジェクト型ではないが、歴史的互換性のために変更されていない。',
    },
    {
      id: 'js_002',
      q: '1 == "1" と 1 === "1" の結果は？',
      code: null,
      answer: 'true と false',
      dummies: ['false と true', '両方 true', '両方 false'],
      exp: '== は型変換（coercion）が起きるため 1 == "1" は true になる。=== は型も含めて厳密比較するので 1 === "1" は false。基本的に === を使うべき。',
    },
    {
      id: 'js_003',
      q: 'let で宣言した変数のスコープは？',
      code: 'if (true) {\n  let x = 10;\n}\nconsole.log(x); // ?',
      answer: 'ブロックスコープ（ReferenceError）',
      dummies: ['関数スコープ（10が出る）', 'グローバルスコープ（10が出る）', 'ファイルスコープ'],
    exp: 'let と const はブロックスコープ（{} の内側）。{} の外からアクセスすると ReferenceError になる。var は関数スコープで {} を無視するため、let/const が推奨される。',
    },
    {
      id: 'js_004',
      q: '[1,2,3].map(n => n * 2) の結果は？',
      code: null,
      answer: '[2, 4, 6]（新しい配列）',
      dummies: ['元の配列を変更して undefined', '合計値 12 を返す', '[1, 2, 3, 2, 4, 6]'],
      exp: 'map() は元の配列を変更せず、変換した新しい配列を返す。配列を変換するのが map、副作用（画面表示など）には forEach を使う。',
    },
    {
      id: 'js_005',
      q: '(a, b) => a + b は何を返す？',
      code: null,
      answer: 'a + b の値（暗黙の return）',
      dummies: ['常に undefined を返す', 'オブジェクト { a + b }', '構文エラーになる'],
      exp: 'アロー関数で本体が単一の式の場合、{} と return を省略できる（暗黙の return）。{ return a + b; } と書いても同じ意味。',
    },
    {
      id: 'js_006',
      q: 'Promiseのエラーをキャッチするメソッドは？',
      code: 'fetch(url)\n  .then(res => res.json())\n  .???(err => console.error(err))',
      answer: 'catch',
      dummies: ['error', 'fail', 'reject'],
      exp: '.catch() は Promise チェーンのいずれかで発生したエラーをキャッチする。async/await では try/catch でエラーハンドリングできる。',
    },
    {
      id: 'js_007',
      q: '表示の順序は？',
      code: 'console.log("A");\nsetTimeout(() => console.log("B"), 0);\nconsole.log("C");',
      answer: 'A → C → B',
      dummies: ['A → B → C', 'B → A → C', '同時に A, B, C'],
      exp: 'setTimeout は非同期。コールバックはコールスタックが空になってから実行される（イベントループ）。0ms でも同期コードより後になる。',
    },
    {
      id: 'js_008',
      q: 'オブジェクト → JSON文字列 に変換するメソッドは？',
      code: 'const obj = { name: "Alice" }',
      answer: 'JSON.stringify(obj)',
      dummies: ['JSON.parse(obj)', 'obj.toJSON()', 'JSON.encode(obj)'],
      exp: 'JSON.stringify() はオブジェクト → JSON文字列。JSON.parse() は逆で JSON文字列 → オブジェクト。Stringify = 文字列化、と覚えよう。',
    },
    {
      id: 'js_009',
      q: 'const で宣言した配列に要素を追加できる？',
      code: 'const arr = [1, 2];\narr.push(3);',
      answer: 'できる（再代入はできないが変更は可能）',
      dummies: ['できない（TypeError になる）', 'できるが元の配列は変わらない', '宣言後は完全に不変（frozen）'],
      exp: 'const は再代入（arr = [...]）を禁止するが、配列やオブジェクトの中身の変更は許可される。完全に変更不可にするには Object.freeze() を使う。',
    },
    {
      id: 'js_010',
      q: 'スプレッド構文 [...a, ...b] は何をする？',
      code: 'const a = [1, 2];\nconst b = [3, 4];\nconst c = [...a, ...b];',
      answer: '[1, 2, 3, 4]（配列を結合）',
      dummies: ['[[1,2],[3,4]]（ネスト）', 'エラーが発生する', '[1, 2]（最初のみ）'],
      exp: '... は配列やオブジェクトを展開するスプレッド構文。配列の結合・コピー、関数の引数展開など用途が広い。',
    },
  ],

  // ==================== HTML ====================
  html: [
    {
      id: 'html_001',
      q: 'HTML5 の文書型宣言は？',
      code: null,
      answer: '<!DOCTYPE html>',
      dummies: ['<html version="5">', '<?xml version="1.0"?>', '<head type="html5">'],
      exp: '<!DOCTYPE html> はブラウザに「HTML5 として解釈して」と伝える宣言。これがないと後方互換モード（quirks mode）になりレイアウトが崩れることがある。',
    },
    {
      id: 'html_002',
      q: 'ブログ記事の本文を囲むセマンティックなタグは？',
      code: null,
      answer: '<article>',
      dummies: ['<div>', '<section>', '<content>'],
      exp: '<article> は独立したコンテンツ（記事・ニュースなど）を表す。<div> は意味のないコンテナ。セマンティクスはSEOとスクリーンリーダーのアクセシビリティに重要。',
    },
    {
      id: 'html_003',
      q: 'リンクの URL を指定する <a> の属性は？',
      code: '<a ???="https://example.com">リンク</a>',
      answer: 'href',
      dummies: ['src', 'url', 'link'],
      exp: 'href（Hypertext REFerence）でリンク先 URL を指定する。src は <img> や <script> などのリソース読み込みに使う。',
    },
    {
      id: 'html_004',
      q: 'チェックボックスを作る HTML は？',
      code: null,
      answer: '<input type="checkbox">',
      dummies: ['<checkbox>', '<input type="check">', '<toggle>'],
      exp: 'チェックボックス・ラジオボタン・テキストフィールドなどは全て <input> の type 属性で区別する。<checkbox> というタグは存在しない。',
    },
    {
      id: 'html_005',
      q: '画像が読み込めないときの代替テキストを指定する属性は？',
      code: '<img src="photo.jpg" ???="プロフィール写真">',
      answer: 'alt',
      dummies: ['title', 'caption', 'fallback'],
      exp: 'alt（代替テキスト）は画像が読み込めないときや、スクリーンリーダーが読み上げるときに使う。アクセシビリティのために重要。装飾画像は alt="" と書く。',
    },
    {
      id: 'html_006',
      q: '<span> はどちらの要素タイプ？',
      code: null,
      answer: 'インライン要素',
      dummies: ['ブロック要素', 'インラインブロック要素', 'フレックス要素'],
      exp: '<span> はデフォルトでインライン要素。テキストの一部をスタイリングするために使う。ブロック要素（<div>など）は縦に積まれ、インライン要素は横に並ぶ。',
    },
    {
      id: 'html_007',
      q: 'テーブルの通常データセルのタグは？',
      code: '<tr>\n  <???>データ</???>\n</tr>',
      answer: '<td>',
      dummies: ['<th>', '<tc>', '<cell>'],
      exp: '<td>（table data）が通常のセル、<th>（table header）がヘッダーセル（太字・中央揃え）。<tr> が行で、その中に <td> や <th> を入れる。',
    },
    {
      id: 'html_008',
      q: 'HTML コメントの正しい書き方は？',
      code: null,
      answer: '<!-- コメント -->',
      dummies: ['// コメント', '/* コメント */', '# コメント'],
      exp: 'HTML のコメントは <!-- --> で囲む。<script> 内は JS のコメント（//）、<style> 内は CSS のコメント（/* */）を使う。',
    },
    {
      id: 'html_009',
      q: '<form> でデータを送信先に指定する属性は？',
      code: '<form ???="/submit" method="post">',
      answer: 'action',
      dummies: ['href', 'target', 'url'],
      exp: 'action はフォームの送信先 URL を指定する。method はHTTPメソッド（get または post）を指定する。',
    },
    {
      id: 'html_010',
      q: '<meta charset="UTF-8"> の役割は？',
      code: null,
      answer: '文字エンコードを指定する',
      dummies: ['ページのタイトルを設定する', 'CSSを読み込む', 'ビューポートを設定する'],
      exp: 'charset で文字コードを指定する。UTF-8 にしておけば日本語など多言語が正しく表示される。<head> の最初に書くのがベストプラクティス。',
    },
  ],

  // ==================== CSS ====================
  css: [
    {
      id: 'css_001',
      q: 'margin と padding の違いは？',
      code: null,
      answer: 'margin:外側のスペース / padding:内側',
      dummies: ['margin:内側のスペース / padding:外側', '違いはない（どちらも同じ）', 'marginは縦のみ有効'],
      exp: 'ボックスモデル：外 = margin → border → padding → コンテンツ。背景色は padding 領域まで適用され、margin には適用されない。',
    },
    {
      id: 'css_002',
      q: 'Flexbox で主軸方向の配置を制御するプロパティは？',
      code: '.box { display: flex; ???: center; }',
      answer: 'justify-content',
      dummies: ['align-items', 'align-content', 'flex-align'],
      exp: 'justify-content は主軸（デフォルトは横）方向の配置。align-items は交差軸（デフォルトは縦）方向。よく混同するので「justify = 主軸」と覚えよう。',
    },
    {
      id: 'css_003',
      q: 'position: absolute の基準となる要素は？',
      code: null,
      answer: '最も近い position が static 以外の祖先要素',
      dummies: ['常に <body>', '常に親要素', '常にビューポート'],
      exp: 'absolute 要素は position が relative/absolute/fixed/sticky の最も近い祖先を基準に配置される。そのような祖先がない場合は <html> が基準になる。',
    },
    {
      id: 'css_004',
      q: 'CSS で最も優先度が高いのはどれ？',
      code: null,
      answer: '!important',
      dummies: ['インラインスタイル', 'IDセレクタ (#id)', 'クラスセレクタ (.class)'],
      exp: '優先度の順：!important > インラインスタイル > IDセレクタ > クラスセレクタ > 要素セレクタ。!important は緊急手段で乱用は禁物。',
    },
    {
      id: 'css_005',
      q: 'CSS Grid で3列均等に分割するには？',
      code: '.grid {\n  display: grid;\n  grid-template-columns: ???;\n}',
      answer: 'repeat(3, 1fr)',
      dummies: ['3fr', 'auto auto auto', 'grid(3, equal)'],
      exp: 'fr（fraction）は使用可能な空間の比率。repeat(3, 1fr) は 1fr 1fr 1fr と同じ意味。auto は中身に合わせた幅になる。',
    },
    {
      id: 'css_006',
      q: ':hover と :focus の違いは？',
      code: null,
      answer: ':hover=マウスオーバー時 / :focus=フォーカス時',
      dummies: [':hover=クリック時 / :focus=ホバー時', '違いはない', ':hover=リンク専用 / :focus=フォーム専用'],
      exp: ':focus はキーボードユーザーがタブキーで移動したときに有効になる。アクセシビリティのために :hover だけでなく :focus も必ずスタイリングすること。',
    },
    {
      id: 'css_007',
      q: '0.3秒かけて opacity を変化させる transition は？',
      code: '.btn:hover { opacity: 0.5; }',
      answer: 'transition: opacity 0.3s',
      dummies: ['animation: opacity 0.3s', 'transform: opacity 0.3s', 'transition-time: 0.3s'],
      exp: 'transition の書式は「プロパティ 時間 タイミング 遅延」。animation はより複雑なキーフレームアニメーションに使う。',
    },
    {
      id: 'css_008',
      q: 'display:none と visibility:hidden の違いは？',
      code: null,
      answer: 'none=スペースも消える / hidden=スペースは残る',
      dummies: ['違いはない（どちらも同じ）', 'none=一時的 / hidden=永続的', 'none=子も消える / hidden=自分だけ'],
      exp: 'display:none は要素が存在しないかのようにレイアウト。visibility:hidden は見えないが領域は占有したまま。opacity:0 は透明だがクリックできる。',
    },
    {
      id: 'css_009',
      q: 'overflow: hidden を使う主な目的は？',
      code: null,
      answer: 'はみ出したコンテンツを隠す・float の回り込みを解除',
      dummies: ['フォントサイズを自動縮小する', '要素を非表示にする（visibility:hidden と同じ）', 'スクロールを無効にする'],
      exp: 'overflow:hidden ははみ出した内容を切り取る。また float した子要素を持つ親に使うと高さが崩れる問題（float collapse）を解決できる。',
    },
    {
      id: 'css_010',
      q: 'rem 単位は何を基準にする？',
      code: 'font-size: 1.5rem;',
      answer: 'ルート要素（html）のフォントサイズ',
      dummies: ['親要素のフォントサイズ', 'ビューポートの幅', 'ブラウザの画面サイズ'],
      exp: 'rem（root em）はルート要素 <html> のフォントサイズ基準。em は親要素基準で入れ子になるとサイズが複雑になる。レスポンシブデザインでは rem が安全。',
    },
  ],

  // ==================== SQL ====================
  sql: [
    {
      id: 'sql_001',
      q: 'テーブルの全データを取得するSQL文は？',
      code: null,
      answer: 'SELECT * FROM テーブル名',
      dummies: ['GET ALL FROM テーブル名', 'FETCH * FROM テーブル名', 'READ * FROM テーブル名'],
      exp: 'SELECT は列を指定、* は全列。FROM でテーブルを指定する。本番環境では * より必要な列だけ指定する方が効率的（転送量・速度）。',
    },
    {
      id: 'sql_002',
      q: '行を絞り込む SQL のキーワードは？',
      code: 'SELECT * FROM users\n??? age > 20',
      answer: 'WHERE',
      dummies: ['HAVING', 'FILTER', 'CONDITION'],
      exp: 'WHERE は個々の行を絞り込む。HAVING は GROUP BY 後のグループを絞り込む（COUNT > 5 などの集計条件に使う）。',
    },
    {
      id: 'sql_003',
      q: 'INNER JOIN と LEFT JOIN の違いは？',
      code: null,
      answer: 'INNER=一致した行のみ / LEFT=左テーブル全行',
      dummies: ['INNER=全行 / LEFT=一致した行のみ', '違いはない', 'INNER=高速 / LEFT=低速'],
      exp: 'INNER JOIN：両テーブルで一致する行のみ返す。LEFT JOIN：左（FROM）テーブルの全行を保持し、一致しない右側は NULL になる。',
    },
    {
      id: 'sql_004',
      q: '行数を数える集計関数は？',
      code: 'SELECT ???(*) FROM orders',
      answer: 'COUNT',
      dummies: ['SUM', 'TOTAL', 'NUM'],
      exp: 'COUNT(*) は NULL を含む全行数、COUNT(列名) は NULL を除いた行数。SUM は数値の合計、AVG は平均、MAX/MIN は最大・最小値。',
    },
    {
      id: 'sql_005',
      q: '特定の列でグループ化して集計するには？',
      code: 'SELECT category, COUNT(*)\nFROM products\n??? category',
      answer: 'GROUP BY',
      dummies: ['ORDER BY', 'CLUSTER BY', 'PARTITION BY'],
      exp: 'GROUP BY で同じ値を持つ行をまとめ、COUNT や SUM などで集計できる。SELECT に書けるのは GROUP BY の列か集計関数のみ。',
    },
    {
      id: 'sql_006',
      q: '結果を価格の降順で並べるには？',
      code: 'SELECT * FROM products\nORDER BY price ???',
      answer: 'DESC',
      dummies: ['DOWN', 'REVERSE', 'LOWER'],
      exp: 'ORDER BY はデフォルトで昇順（ASC）。降順は DESC（descending）。複数列も ORDER BY price DESC, name ASC のように指定できる。',
    },
    {
      id: 'sql_007',
      q: 'データを挿入する SQL の構文は？',
      code: null,
      answer: 'INSERT INTO 表名 (列) VALUES (値)',
      dummies: ['ADD INTO 表名 (列) VALUES (値)', 'INSERT 表名 SET 列 = 値', 'CREATE ROW IN 表名 VALUES (値)'],
      exp: 'INSERT INTO で新しい行を追加する。列名を省略すると全列に値を指定する必要がある。複数行挿入は VALUES の後にカンマ区切りで続けられる。',
    },
    {
      id: 'sql_008',
      q: 'UPDATE で WHERE を省略するとどうなる？',
      code: 'UPDATE users SET name = "Alice"\n-- WHERE id = 1 を省略',
      answer: '全行が更新されてしまう',
      dummies: ['最初の1行だけ更新される', 'エラーになる', 'NULL の行だけ更新される'],
      exp: 'WHERE を省略した UPDATE はテーブルの全行を更新する非常に危険なクエリ。本番操作前に SELECT でどの行が対象か確認するのが鉄則。',
    },
    {
      id: 'sql_009',
      q: '重複を除いた結果を取得するキーワードは？',
      code: 'SELECT ??? city FROM users',
      answer: 'DISTINCT',
      dummies: ['UNIQUE', 'NODUP', 'SINGLE'],
      exp: 'SELECT DISTINCT で重複を除いた一意の値だけ返す。GROUP BY でも似たことができるが、集計なしで一意の値が欲しい場合は DISTINCT が簡潔。',
    },
    {
      id: 'sql_010',
      q: '集計結果を条件で絞り込むキーワードは？',
      code: 'SELECT category, COUNT(*)\nFROM products\nGROUP BY category\n??? COUNT(*) > 5',
      answer: 'HAVING',
      dummies: ['WHERE', 'FILTER', 'CONDITION'],
      exp: 'HAVING は GROUP BY 後のグループに条件を付ける。WHERE は集計前の行に条件を付ける。集計関数（COUNT, SUM など）を条件にするときは HAVING を使う。',
    },
  ],

  // ==================== Git ====================
  git: [
    {
      id: 'git_001',
      q: '新しい Git リポジトリを初期化するコマンドは？',
      code: null,
      answer: 'git init',
      dummies: ['git create', 'git start', 'git new'],
      exp: 'git init でカレントディレクトリに .git フォルダが作られ管理が始まる。既存のリポジトリを複製するなら git clone を使う。',
    },
    {
      id: 'git_002',
      q: 'ファイルをステージングエリアに追加するコマンドは？',
      code: null,
      answer: 'git add',
      dummies: ['git stage', 'git commit', 'git push'],
      exp: 'Gitの流れ：変更 → git add（ステージング）→ git commit（確定）→ git push（リモートへ）。add はコミットに含める変更を選択する段階。',
    },
    {
      id: 'git_003',
      q: 'リモートの main ブランチにプッシュするコマンドは？',
      code: null,
      answer: 'git push origin main',
      dummies: ['git upload origin main', 'git send main', 'git push main origin'],
      exp: 'git push <リモート名> <ブランチ名>。origin はデフォルトのリモートリポジトリの名前。初回は -u フラグで追跡設定する（git push -u origin main）。',
    },
    {
      id: 'git_004',
      q: 'git pull と git fetch の違いは？',
      code: null,
      answer: 'fetch=ダウンロードのみ / pull=fetch+merge',
      dummies: ['fetch=全ブランチ / pull=現在のブランチのみ', '違いはない', 'fetch=高速 / pull=低速'],
      exp: 'git fetch はリモートの変更をダウンロードするが、ローカルには適用しない。git pull = fetch + merge（またはrebase）。確認してからマージしたい場合は fetch を使う。',
    },
    {
      id: 'git_005',
      q: 'ブランチを作りながら同時に切り替えるコマンドは？',
      code: null,
      answer: 'git checkout -b ブランチ名',
      dummies: ['git branch --new ブランチ名', 'git create ブランチ名', 'git branch ブランチ名（切り替えなし）'],
      exp: 'git checkout -b は「ブランチ作成 + 切り替え」を一度に行う。新しい構文では git switch -c ブランチ名 でも同じことができる。',
    },
    {
      id: 'git_006',
      q: 'コミットせずに変更を一時退避するコマンドは？',
      code: null,
      answer: 'git stash',
      dummies: ['git save', 'git hide', 'git temp'],
      exp: 'git stash は作業中の変更を一時退避する。git stash pop で復元。別ブランチに切り替えたいが commit したくないときに便利。',
    },
    {
      id: 'git_007',
      q: 'git merge と git rebase の主な違いは？',
      code: null,
      answer: 'merge=マージコミット作成 / rebase=履歴を線形に',
      dummies: ['merge=高速 / rebase=低速', 'merge=ローカル / rebase=リモート用', '違いはない'],
      exp: 'rebase は履歴がきれいになるが、公開済みブランチでは使わないこと（他の人の履歴が壊れる）。個人ブランチのクリーンアップには rebase、共有ブランチには merge が安全。',
    },
    {
      id: 'git_008',
      q: '.gitignore に書くと何ができる？',
      code: 'node_modules/\n.env\n*.log',
      answer: 'Git に追跡させないファイルを指定できる',
      dummies: ['Git を完全に無効化できる', 'コミットを自動的に削除する', '大きなファイルを圧縮して管理する'],
      exp: '.gitignore はGitに無視させるファイルを指定する。node_modules や .env（秘密情報）、ビルド成果物などを除外するのが一般的。.gitignore 自体はコミットする。',
    },
    {
      id: 'git_009',
      q: '直前のコミットを取り消してステージングに戻すコマンドは？',
      code: null,
      answer: 'git reset --soft HEAD~1',
      dummies: ['git undo', 'git revert HEAD', 'git reset --hard HEAD~1'],
      exp: '--soft はコミットだけ取り消し、変更はステージングに残る。--mixed（デフォルト）は変更が作業ディレクトリに残る。--hard は変更ごと消える（危険）。',
    },
    {
      id: 'git_010',
      q: 'リポジトリの変更状態を確認するコマンドは？',
      code: null,
      answer: 'git status',
      dummies: ['git info', 'git check', 'git show'],
      exp: 'git status はステージング状態、変更されたファイル、追跡されていないファイルなどを表示する。作業前後に習慣的に確認するのが良い。',
    },
  ],

};
