// ===================================================
// コード道場 — 問題データ
// ===================================================

const TOPICS = [
  { id: 'python',     name: 'Python',     icon: '🐍', desc: '構文・型・組み込み関数' },
  { id: 'javascript', name: 'JavaScript', icon: '🟡', desc: '型・スコープ・非同期' },
  { id: 'html',       name: 'HTML',       icon: '🌐', desc: 'タグ・属性・構造' },
  { id: 'css',        name: 'CSS',        icon: '🎨', desc: 'スタイル・Flex・Grid' },
  { id: 'sql',        name: 'SQL',        icon: '🗃', desc: 'クエリ・結合・集計' },
  { id: 'git',        name: 'Git',        icon: '🌿', desc: 'コマンド・ブランチ' },
  { id: 'tokipona',   name: 'トキポナ語', icon: '🌸', desc: '全120単語・語彙' },
];

const QUESTIONS = {

  // ==================== Python ====================
  python: [
    {
      id: 'py_001',
      q: 'リストの要素数を取得する関数は？',
      code: 'items = ["a", "b", "c"]',
      answer: 'len(items)',
      dummies: ['items.length', 'size(items)', 'items.count()'],
      exp: 'len() はリスト・文字列・辞書などの要素数を返す組み込み関数。JavaScript の .length プロパティとは異なり、関数として呼ぶ点に注意。',
    },
    {
      id: 'py_002',
      q: '3.14 のデータ型は？',
      code: 'print(type(3.14))',
      answer: 'float',
      dummies: ['double', 'int', 'decimal'],
      exp: 'Python の小数は float 型。Java などにある double 型は Python には存在しない。type() で確認すると <class \'float\'> と表示される。',
    },
    {
      id: 'py_003',
      q: 'このコードの出力は？',
      code: 'print([x**2 for x in range(3)])',
      answer: '[0, 1, 4]',
      dummies: ['[1, 4, 9]', '[0, 1, 2]', '[0, 2, 4]'],
      exp: 'range(3) は 0, 1, 2 を生成する。0²=0, 1²=1, 2²=4。これはリスト内包表記と言い、for ループを1行で書ける Python の重要な機能。',
    },
    {
      id: 'py_004',
      q: 'キーが存在しないときデフォルト値を返すメソッドは？',
      code: 'd = {"a": 1}\nd.???("b", 0)  # → 0',
      answer: 'get',
      dummies: ['fetch', 'find', 'default'],
      exp: 'd.get(key, default) はキーが存在しなければ default を返す。d["b"] と書くと KeyError が起きる。',
    },
    {
      id: 'py_005',
      q: 'このf文字列の出力は？',
      code: 'name = "世界"\nprint(f"Hello, {name}!")',
      answer: 'Hello, 世界!',
      dummies: ['Hello, {name}!', 'f"Hello, 世界!"', 'Hello, name!'],
      exp: 'f文字列（f-string）は Python 3.6 以降の機能。f"..." の中の {} に変数や式を直接埋め込める。',
    },
    {
      id: 'py_006',
      q: 'リストの逆順コピーを返すスライスは？',
      code: 'items = [1, 2, 3, 4, 5]',
      answer: 'items[::-1]',
      dummies: ['items.reverse()', 'items[-1:]', 'reversed(items)'],
      exp: '[::-1] はステップ -1 で全体をスライスし、逆順の新しいリストを返す。items.reverse() は元を変更（in-place）し、返り値は None。',
    },
    {
      id: 'py_007',
      q: 'def func(*args) の *args が受け取るものは？',
      code: null,
      answer: '可変長の位置引数（タプル）',
      dummies: ['可変長のキーワード引数（辞書）', '任意の1つの引数', '引数を展開して渡す演算子'],
      exp: '*args は任意の数の位置引数をタプルとして受け取る。**kwargs はキーワード引数を辞書で受け取る。',
    },
    {
      id: 'py_008',
      q: 'このコードの出力は？',
      code: 'a = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)',
      answer: '[1, 2, 3, 4]',
      dummies: ['[1, 2, 3]', 'エラーが発生する', '[1, 2, 3, [4]]'],
      exp: 'b = a はリストのコピーではなく、同じオブジェクトへの参照を代入する。b を変更すると a も変わる。コピーするには a[:] か list(a) を使う。',
    },
    {
      id: 'py_009',
      q: 'None との比較に使うべき演算子は？',
      code: 'x = None\nif x ??? None:',
      answer: 'is',
      dummies: ['==', '===', 'equals'],
      exp: 'None との比較には == ではなく is を使うのがPython流。is は同一オブジェクトかを確認する。PEP 8 でも is None が推奨されている。',
    },
    {
      id: 'py_010',
      q: 'このコードの出力は？',
      code: 'print("abc" * 3)',
      answer: 'abcabcabc',
      dummies: ['abc3', 'エラーが発生する', 'abc abc abc'],
      exp: 'Python では文字列に整数を掛けると、その回数分繰り返した文字列が返る。リストでも同様に [0] * 3 → [0, 0, 0] のように使える。',
    },
  ],

  // ==================== JavaScript ====================
  javascript: [
    {
      id: 'js_001',
      q: 'typeof null の結果は？',
      code: 'console.log(typeof null)',
      answer: '"object"',
      dummies: ['"null"', '"undefined"', '"string"'],
      exp: 'typeof null が "object" を返すのはJavaScript初期の有名なバグ。null はオブジェクト型ではないが、歴史的互換性のために変更されていない。',
    },
    {
      id: 'js_002',
      q: '1 == "1" と 1 === "1" の結果は？',
      code: null,
      answer: 'true と false',
      dummies: ['false と true', '両方 true', '両方 false'],
      exp: '== は型変換（coercion）が起きるため 1 == "1" は true になる。=== は型も含めて厳密比較するので 1 === "1" は false。基本的に === を使うべき。',
    },
    {
      id: 'js_003',
      q: 'let で宣言した変数のスコープは？',
      code: 'if (true) {\n  let x = 10;\n}\nconsole.log(x); // ?',
      answer: 'ブロックスコープ（ReferenceError）',
      dummies: ['関数スコープ（10が出る）', 'グローバルスコープ（10が出る）', 'ファイルスコープ'],
    exp: 'let と const はブロックスコープ（{} の内側）。{} の外からアクセスすると ReferenceError になる。var は関数スコープで {} を無視するため、let/const が推奨される。',
    },
    {
      id: 'js_004',
      q: '[1,2,3].map(n => n * 2) の結果は？',
      code: null,
      answer: '[2, 4, 6]（新しい配列）',
      dummies: ['元の配列を変更して undefined', '合計値 12 を返す', '[1, 2, 3, 2, 4, 6]'],
      exp: 'map() は元の配列を変更せず、変換した新しい配列を返す。配列を変換するのが map、副作用（画面表示など）には forEach を使う。',
    },
    {
      id: 'js_005',
      q: '(a, b) => a + b は何を返す？',
      code: null,
      answer: 'a + b の値（暗黙の return）',
      dummies: ['常に undefined を返す', 'オブジェクト { a + b }', '構文エラーになる'],
      exp: 'アロー関数で本体が単一の式の場合、{} と return を省略できる（暗黙の return）。{ return a + b; } と書いても同じ意味。',
    },
    {
      id: 'js_006',
      q: 'Promiseのエラーをキャッチするメソッドは？',
      code: 'fetch(url)\n  .then(res => res.json())\n  .???(err => console.error(err))',
      answer: 'catch',
      dummies: ['error', 'fail', 'reject'],
      exp: '.catch() は Promise チェーンのいずれかで発生したエラーをキャッチする。async/await では try/catch でエラーハンドリングできる。',
    },
    {
      id: 'js_007',
      q: '表示の順序は？',
      code: 'console.log("A");\nsetTimeout(() => console.log("B"), 0);\nconsole.log("C");',
      answer: 'A → C → B',
      dummies: ['A → B → C', 'B → A → C', '同時に A, B, C'],
      exp: 'setTimeout は非同期。コールバックはコールスタックが空になってから実行される（イベントループ）。0ms でも同期コードより後になる。',
    },
    {
      id: 'js_008',
      q: 'オブジェクト → JSON文字列 に変換するメソッドは？',
      code: 'const obj = { name: "Alice" }',
      answer: 'JSON.stringify(obj)',
      dummies: ['JSON.parse(obj)', 'obj.toJSON()', 'JSON.encode(obj)'],
      exp: 'JSON.stringify() はオブジェクト → JSON文字列。JSON.parse() は逆で JSON文字列 → オブジェクト。Stringify = 文字列化、と覚えよう。',
    },
    {
      id: 'js_009',
      q: 'const で宣言した配列に要素を追加できる？',
      code: 'const arr = [1, 2];\narr.push(3);',
      answer: 'できる（再代入はできないが変更は可能）',
      dummies: ['できない（TypeError になる）', 'できるが元の配列は変わらない', '宣言後は完全に不変（frozen）'],
      exp: 'const は再代入（arr = [...]）を禁止するが、配列やオブジェクトの中身の変更は許可される。完全に変更不可にするには Object.freeze() を使う。',
    },
    {
      id: 'js_010',
      q: 'スプレッド構文 [...a, ...b] は何をする？',
      code: 'const a = [1, 2];\nconst b = [3, 4];\nconst c = [...a, ...b];',
      answer: '[1, 2, 3, 4]（配列を結合）',
      dummies: ['[[1,2],[3,4]]（ネスト）', 'エラーが発生する', '[1, 2]（最初のみ）'],
      exp: '... は配列やオブジェクトを展開するスプレッド構文。配列の結合・コピー、関数の引数展開など用途が広い。',
    },
  ],

  // ==================== HTML ====================
  html: [
    {
      id: 'html_001',
      q: 'HTML5 の文書型宣言は？',
      code: null,
      answer: '<!DOCTYPE html>',
      dummies: ['<html version="5">', '<?xml version="1.0"?>', '<head type="html5">'],
      exp: '<!DOCTYPE html> はブラウザに「HTML5 として解釈して」と伝える宣言。これがないと後方互換モード（quirks mode）になりレイアウトが崩れることがある。',
    },
    {
      id: 'html_002',
      q: 'ブログ記事の本文を囲むセマンティックなタグは？',
      code: null,
      answer: '<article>',
      dummies: ['<div>', '<section>', '<content>'],
      exp: '<article> は独立したコンテンツ（記事・ニュースなど）を表す。<div> は意味のないコンテナ。セマンティクスはSEOとスクリーンリーダーのアクセシビリティに重要。',
    },
    {
      id: 'html_003',
      q: 'リンクの URL を指定する <a> の属性は？',
      code: '<a ???="https://example.com">リンク</a>',
      answer: 'href',
      dummies: ['src', 'url', 'link'],
      exp: 'href（Hypertext REFerence）でリンク先 URL を指定する。src は <img> や <script> などのリソース読み込みに使う。',
    },
    {
      id: 'html_004',
      q: 'チェックボックスを作る HTML は？',
      code: null,
      answer: '<input type="checkbox">',
      dummies: ['<checkbox>', '<input type="check">', '<toggle>'],
      exp: 'チェックボックス・ラジオボタン・テキストフィールドなどは全て <input> の type 属性で区別する。<checkbox> というタグは存在しない。',
    },
    {
      id: 'html_005',
      q: '画像が読み込めないときの代替テキストを指定する属性は？',
      code: '<img src="photo.jpg" ???="プロフィール写真">',
      answer: 'alt',
      dummies: ['title', 'caption', 'fallback'],
      exp: 'alt（代替テキスト）は画像が読み込めないときや、スクリーンリーダーが読み上げるときに使う。アクセシビリティのために重要。装飾画像は alt="" と書く。',
    },
    {
      id: 'html_006',
      q: '<span> はどちらの要素タイプ？',
      code: null,
      answer: 'インライン要素',
      dummies: ['ブロック要素', 'インラインブロック要素', 'フレックス要素'],
      exp: '<span> はデフォルトでインライン要素。テキストの一部をスタイリングするために使う。ブロック要素（<div>など）は縦に積まれ、インライン要素は横に並ぶ。',
    },
    {
      id: 'html_007',
      q: 'テーブルの通常データセルのタグは？',
      code: '<tr>\n  <???>データ</???>\n</tr>',
      answer: '<td>',
      dummies: ['<th>', '<tc>', '<cell>'],
      exp: '<td>（table data）が通常のセル、<th>（table header）がヘッダーセル（太字・中央揃え）。<tr> が行で、その中に <td> や <th> を入れる。',
    },
    {
      id: 'html_008',
      q: 'HTML コメントの正しい書き方は？',
      code: null,
      answer: '<!-- コメント -->',
      dummies: ['// コメント', '/* コメント */', '# コメント'],
      exp: 'HTML のコメントは <!-- --> で囲む。<script> 内は JS のコメント（//）、<style> 内は CSS のコメント（/* */）を使う。',
    },
    {
      id: 'html_009',
      q: '<form> でデータを送信先に指定する属性は？',
      code: '<form ???="/submit" method="post">',
      answer: 'action',
      dummies: ['href', 'target', 'url'],
      exp: 'action はフォームの送信先 URL を指定する。method はHTTPメソッド（get または post）を指定する。',
    },
    {
      id: 'html_010',
      q: '<meta charset="UTF-8"> の役割は？',
      code: null,
      answer: '文字エンコードを指定する',
      dummies: ['ページのタイトルを設定する', 'CSSを読み込む', 'ビューポートを設定する'],
      exp: 'charset で文字コードを指定する。UTF-8 にしておけば日本語など多言語が正しく表示される。<head> の最初に書くのがベストプラクティス。',
    },
  ],

  // ==================== CSS ====================
  css: [
    {
      id: 'css_001',
      q: 'margin と padding の違いは？',
      code: null,
      answer: 'margin:外側のスペース / padding:内側',
      dummies: ['margin:内側のスペース / padding:外側', '違いはない（どちらも同じ）', 'marginは縦のみ有効'],
      exp: 'ボックスモデル：外 = margin → border → padding → コンテンツ。背景色は padding 領域まで適用され、margin には適用されない。',
    },
    {
      id: 'css_002',
      q: 'Flexbox で主軸方向の配置を制御するプロパティは？',
      code: '.box { display: flex; ???: center; }',
      answer: 'justify-content',
      dummies: ['align-items', 'align-content', 'flex-align'],
      exp: 'justify-content は主軸（デフォルトは横）方向の配置。align-items は交差軸（デフォルトは縦）方向。よく混同するので「justify = 主軸」と覚えよう。',
    },
    {
      id: 'css_003',
      q: 'position: absolute の基準となる要素は？',
      code: null,
      answer: '最も近い position が static 以外の祖先要素',
      dummies: ['常に <body>', '常に親要素', '常にビューポート'],
      exp: 'absolute 要素は position が relative/absolute/fixed/sticky の最も近い祖先を基準に配置される。そのような祖先がない場合は <html> が基準になる。',
    },
    {
      id: 'css_004',
      q: 'CSS で最も優先度が高いのはどれ？',
      code: null,
      answer: '!important',
      dummies: ['インラインスタイル', 'IDセレクタ (#id)', 'クラスセレクタ (.class)'],
      exp: '優先度の順：!important > インラインスタイル > IDセレクタ > クラスセレクタ > 要素セレクタ。!important は緊急手段で乱用は禁物。',
    },
    {
      id: 'css_005',
      q: 'CSS Grid で3列均等に分割するには？',
      code: '.grid {\n  display: grid;\n  grid-template-columns: ???;\n}',
      answer: 'repeat(3, 1fr)',
      dummies: ['3fr', 'auto auto auto', 'grid(3, equal)'],
      exp: 'fr（fraction）は使用可能な空間の比率。repeat(3, 1fr) は 1fr 1fr 1fr と同じ意味。auto は中身に合わせた幅になる。',
    },
    {
      id: 'css_006',
      q: ':hover と :focus の違いは？',
      code: null,
      answer: ':hover=マウスオーバー時 / :focus=フォーカス時',
      dummies: [':hover=クリック時 / :focus=ホバー時', '違いはない', ':hover=リンク専用 / :focus=フォーム専用'],
      exp: ':focus はキーボードユーザーがタブキーで移動したときに有効になる。アクセシビリティのために :hover だけでなく :focus も必ずスタイリングすること。',
    },
    {
      id: 'css_007',
      q: '0.3秒かけて opacity を変化させる transition は？',
      code: '.btn:hover { opacity: 0.5; }',
      answer: 'transition: opacity 0.3s',
      dummies: ['animation: opacity 0.3s', 'transform: opacity 0.3s', 'transition-time: 0.3s'],
      exp: 'transition の書式は「プロパティ 時間 タイミング 遅延」。animation はより複雑なキーフレームアニメーションに使う。',
    },
    {
      id: 'css_008',
      q: 'display:none と visibility:hidden の違いは？',
      code: null,
      answer: 'none=スペースも消える / hidden=スペースは残る',
      dummies: ['違いはない（どちらも同じ）', 'none=一時的 / hidden=永続的', 'none=子も消える / hidden=自分だけ'],
      exp: 'display:none は要素が存在しないかのようにレイアウト。visibility:hidden は見えないが領域は占有したまま。opacity:0 は透明だがクリックできる。',
    },
    {
      id: 'css_009',
      q: 'overflow: hidden を使う主な目的は？',
      code: null,
      answer: 'はみ出したコンテンツを隠す・float の回り込みを解除',
      dummies: ['フォントサイズを自動縮小する', '要素を非表示にする（visibility:hidden と同じ）', 'スクロールを無効にする'],
      exp: 'overflow:hidden ははみ出した内容を切り取る。また float した子要素を持つ親に使うと高さが崩れる問題（float collapse）を解決できる。',
    },
    {
      id: 'css_010',
      q: 'rem 単位は何を基準にする？',
      code: 'font-size: 1.5rem;',
      answer: 'ルート要素（html）のフォントサイズ',
      dummies: ['親要素のフォントサイズ', 'ビューポートの幅', 'ブラウザの画面サイズ'],
      exp: 'rem（root em）はルート要素 <html> のフォントサイズ基準。em は親要素基準で入れ子になるとサイズが複雑になる。レスポンシブデザインでは rem が安全。',
    },
  ],

  // ==================== SQL ====================
  sql: [
    {
      id: 'sql_001',
      q: 'テーブルの全データを取得するSQL文は？',
      code: null,
      answer: 'SELECT * FROM テーブル名',
      dummies: ['GET ALL FROM テーブル名', 'FETCH * FROM テーブル名', 'READ * FROM テーブル名'],
      exp: 'SELECT は列を指定、* は全列。FROM でテーブルを指定する。本番環境では * より必要な列だけ指定する方が効率的（転送量・速度）。',
    },
    {
      id: 'sql_002',
      q: '行を絞り込む SQL のキーワードは？',
      code: 'SELECT * FROM users\n??? age > 20',
      answer: 'WHERE',
      dummies: ['HAVING', 'FILTER', 'CONDITION'],
      exp: 'WHERE は個々の行を絞り込む。HAVING は GROUP BY 後のグループを絞り込む（COUNT > 5 などの集計条件に使う）。',
    },
    {
      id: 'sql_003',
      q: 'INNER JOIN と LEFT JOIN の違いは？',
      code: null,
      answer: 'INNER=一致した行のみ / LEFT=左テーブル全行',
      dummies: ['INNER=全行 / LEFT=一致した行のみ', '違いはない', 'INNER=高速 / LEFT=低速'],
      exp: 'INNER JOIN：両テーブルで一致する行のみ返す。LEFT JOIN：左（FROM）テーブルの全行を保持し、一致しない右側は NULL になる。',
    },
    {
      id: 'sql_004',
      q: '行数を数える集計関数は？',
      code: 'SELECT ???(*) FROM orders',
      answer: 'COUNT',
      dummies: ['SUM', 'TOTAL', 'NUM'],
      exp: 'COUNT(*) は NULL を含む全行数、COUNT(列名) は NULL を除いた行数。SUM は数値の合計、AVG は平均、MAX/MIN は最大・最小値。',
    },
    {
      id: 'sql_005',
      q: '特定の列でグループ化して集計するには？',
      code: 'SELECT category, COUNT(*)\nFROM products\n??? category',
      answer: 'GROUP BY',
      dummies: ['ORDER BY', 'CLUSTER BY', 'PARTITION BY'],
      exp: 'GROUP BY で同じ値を持つ行をまとめ、COUNT や SUM などで集計できる。SELECT に書けるのは GROUP BY の列か集計関数のみ。',
    },
    {
      id: 'sql_006',
      q: '結果を価格の降順で並べるには？',
      code: 'SELECT * FROM products\nORDER BY price ???',
      answer: 'DESC',
      dummies: ['DOWN', 'REVERSE', 'LOWER'],
      exp: 'ORDER BY はデフォルトで昇順（ASC）。降順は DESC（descending）。複数列も ORDER BY price DESC, name ASC のように指定できる。',
    },
    {
      id: 'sql_007',
      q: 'データを挿入する SQL の構文は？',
      code: null,
      answer: 'INSERT INTO 表名 (列) VALUES (値)',
      dummies: ['ADD INTO 表名 (列) VALUES (値)', 'INSERT 表名 SET 列 = 値', 'CREATE ROW IN 表名 VALUES (値)'],
      exp: 'INSERT INTO で新しい行を追加する。列名を省略すると全列に値を指定する必要がある。複数行挿入は VALUES の後にカンマ区切りで続けられる。',
    },
    {
      id: 'sql_008',
      q: 'UPDATE で WHERE を省略するとどうなる？',
      code: 'UPDATE users SET name = "Alice"\n-- WHERE id = 1 を省略',
      answer: '全行が更新されてしまう',
      dummies: ['最初の1行だけ更新される', 'エラーになる', 'NULL の行だけ更新される'],
      exp: 'WHERE を省略した UPDATE はテーブルの全行を更新する非常に危険なクエリ。本番操作前に SELECT でどの行が対象か確認するのが鉄則。',
    },
    {
      id: 'sql_009',
      q: '重複を除いた結果を取得するキーワードは？',
      code: 'SELECT ??? city FROM users',
      answer: 'DISTINCT',
      dummies: ['UNIQUE', 'NODUP', 'SINGLE'],
      exp: 'SELECT DISTINCT で重複を除いた一意の値だけ返す。GROUP BY でも似たことができるが、集計なしで一意の値が欲しい場合は DISTINCT が簡潔。',
    },
    {
      id: 'sql_010',
      q: '集計結果を条件で絞り込むキーワードは？',
      code: 'SELECT category, COUNT(*)\nFROM products\nGROUP BY category\n??? COUNT(*) > 5',
      answer: 'HAVING',
      dummies: ['WHERE', 'FILTER', 'CONDITION'],
      exp: 'HAVING は GROUP BY 後のグループに条件を付ける。WHERE は集計前の行に条件を付ける。集計関数（COUNT, SUM など）を条件にするときは HAVING を使う。',
    },
  ],

  // ==================== Git ====================
  git: [
    {
      id: 'git_001',
      q: '新しい Git リポジトリを初期化するコマンドは？',
      code: null,
      answer: 'git init',
      dummies: ['git create', 'git start', 'git new'],
      exp: 'git init でカレントディレクトリに .git フォルダが作られ管理が始まる。既存のリポジトリを複製するなら git clone を使う。',
    },
    {
      id: 'git_002',
      q: 'ファイルをステージングエリアに追加するコマンドは？',
      code: null,
      answer: 'git add',
      dummies: ['git stage', 'git commit', 'git push'],
      exp: 'Gitの流れ：変更 → git add（ステージング）→ git commit（確定）→ git push（リモートへ）。add はコミットに含める変更を選択する段階。',
    },
    {
      id: 'git_003',
      q: 'リモートの main ブランチにプッシュするコマンドは？',
      code: null,
      answer: 'git push origin main',
      dummies: ['git upload origin main', 'git send main', 'git push main origin'],
      exp: 'git push <リモート名> <ブランチ名>。origin はデフォルトのリモートリポジトリの名前。初回は -u フラグで追跡設定する（git push -u origin main）。',
    },
    {
      id: 'git_004',
      q: 'git pull と git fetch の違いは？',
      code: null,
      answer: 'fetch=ダウンロードのみ / pull=fetch+merge',
      dummies: ['fetch=全ブランチ / pull=現在のブランチのみ', '違いはない', 'fetch=高速 / pull=低速'],
      exp: 'git fetch はリモートの変更をダウンロードするが、ローカルには適用しない。git pull = fetch + merge（またはrebase）。確認してからマージしたい場合は fetch を使う。',
    },
    {
      id: 'git_005',
      q: 'ブランチを作りながら同時に切り替えるコマンドは？',
      code: null,
      answer: 'git checkout -b ブランチ名',
      dummies: ['git branch --new ブランチ名', 'git create ブランチ名', 'git branch ブランチ名（切り替えなし）'],
      exp: 'git checkout -b は「ブランチ作成 + 切り替え」を一度に行う。新しい構文では git switch -c ブランチ名 でも同じことができる。',
    },
    {
      id: 'git_006',
      q: 'コミットせずに変更を一時退避するコマンドは？',
      code: null,
      answer: 'git stash',
      dummies: ['git save', 'git hide', 'git temp'],
      exp: 'git stash は作業中の変更を一時退避する。git stash pop で復元。別ブランチに切り替えたいが commit したくないときに便利。',
    },
    {
      id: 'git_007',
      q: 'git merge と git rebase の主な違いは？',
      code: null,
      answer: 'merge=マージコミット作成 / rebase=履歴を線形に',
      dummies: ['merge=高速 / rebase=低速', 'merge=ローカル / rebase=リモート用', '違いはない'],
      exp: 'rebase は履歴がきれいになるが、公開済みブランチでは使わないこと（他の人の履歴が壊れる）。個人ブランチのクリーンアップには rebase、共有ブランチには merge が安全。',
    },
    {
      id: 'git_008',
      q: '.gitignore に書くと何ができる？',
      code: 'node_modules/\n.env\n*.log',
      answer: 'Git に追跡させないファイルを指定できる',
      dummies: ['Git を完全に無効化できる', 'コミットを自動的に削除する', '大きなファイルを圧縮して管理する'],
      exp: '.gitignore はGitに無視させるファイルを指定する。node_modules や .env（秘密情報）、ビルド成果物などを除外するのが一般的。.gitignore 自体はコミットする。',
    },
    {
      id: 'git_009',
      q: '直前のコミットを取り消してステージングに戻すコマンドは？',
      code: null,
      answer: 'git reset --soft HEAD~1',
      dummies: ['git undo', 'git revert HEAD', 'git reset --hard HEAD~1'],
      exp: '--soft はコミットだけ取り消し、変更はステージングに残る。--mixed（デフォルト）は変更が作業ディレクトリに残る。--hard は変更ごと消える（危険）。',
    },
    {
      id: 'git_010',
      q: 'リポジトリの変更状態を確認するコマンドは？',
      code: null,
      answer: 'git status',
      dummies: ['git info', 'git check', 'git show'],
      exp: 'git status はステージング状態、変更されたファイル、追跡されていないファイルなどを表示する。作業前後に習慣的に確認するのが良い。',
    },
  ],

  // ==================== トキポナ語（全120単語）====================
  tokipona: [
    { id: 'tp_a',       q: 'この単語の意味は？', code: 'a',       answer: '感嘆詞・強調・感情表現',     dummies: ['否定・ゼロ',         '疑問詞',               'または・選択'],          exp: '感情や強調を表す感嘆詞。文末に付けて意味を強めたり、笑い声「a a a」として使ったりする。' },
    { id: 'tp_akesi',   q: 'この単語の意味は？', code: 'akesi',   answer: '爬虫類・両生類',             dummies: ['魚・水生生物',       '虫・昆虫',             '鳥・飛ぶ動物'],          exp: 'ヘビ・カエル・ワニなど、うろこや粘膜を持つ動物全般。soweli（哺乳類）・kala（魚）・waso（鳥）・pipi（虫）と区別される。' },
    { id: 'tp_ala',     q: 'この単語の意味は？', code: 'ala',     answer: 'なし・ゼロ・否定',           dummies: ['すべて・全体',       '多い・たくさん',       '一つ・唯一'],            exp: '否定を表す最重要単語。「ike ala」で「悪くない」、動詞の後に置いて「〜しない」を表す。' },
    { id: 'tp_alasa',   q: 'この単語の意味は？', code: 'alasa',   answer: '狩る・探す・集める',         dummies: ['食べる・食べ物',     '働く・作る',           '動く・移動する'],        exp: '狩猟・採集・検索など「何かを見つけようとする」行為全般。「alasa e moku」で「食べ物を探す」。' },
    { id: 'tp_ale',     q: 'この単語の意味は？', code: 'ale / ali', answer: 'すべて・全体・宇宙・100', dummies: ['なし・ゼロ',         '一つ・唯一',           '少ない・わずか'],        exp: 'ali とも書く。数体系では「100」を意味し、最大の数。「ale li pona」で「すべては良い」という有名なフレーズ。' },
    { id: 'tp_anpa',    q: 'この単語の意味は？', code: 'anpa',    answer: '下・低い・従う',             dummies: ['上・高い・神聖',     '前・顔・壁',           '後ろ・背後'],            exp: '物理的な「下」と、社会的な「従属・謙虚さ」の両方を表す。' },
    { id: 'tp_ante',    q: 'この単語の意味は？', code: 'ante',    answer: '異なる・変える・別の',       dummies: ['同じ・似ている',     '新しい・追加の',       '古い・以前の'],          exp: '「ante ala」で「変化なし・同じ」。「mi ante e ni」で「私はこれを変える」。' },
    { id: 'tp_anu',     q: 'この単語の意味は？', code: 'anu',     answer: 'または（選択・疑問）',       dummies: ['そして・さらに',     'だけ・しかし',         '〜から・理由'],          exp: '選択肢を並べる接続詞。「ni anu ni?」で「これですか、それですか？」と疑問を作れる。' },
    { id: 'tp_awen',    q: 'この単語の意味は？', code: 'awen',    answer: '保つ・待つ・留まる・安定',   dummies: ['動く・移動する',     '始める・開ける',       '終わる・止まる'],        exp: '継続・安定を表す。補助動詞として「awen pali」で「働き続ける」のようにも使える。' },
    { id: 'tp_e',       q: 'この単語の意味は？', code: 'e',       answer: '直接目的語マーカー',         dummies: ['述語マーカー',       '文脈マーカー',         '主語をつなぐ接続詞'],    exp: '動詞の後に置き、目的語を示す。「mi moku e kili」で「私は果物を食べる」。英語の him/her に相当する位置に置く。' },
    { id: 'tp_en',      q: 'この単語の意味は？', code: 'en',      answer: 'そして（主語を並列）',       dummies: ['または・選択',       '目的語マーカー',       '述語マーカー'],          exp: '主語を並べるときだけ使う。「mi en sina li pali」で「私とあなたは働く」。文中で動詞をつなぐには使わない。' },
    { id: 'tp_esun',    q: 'この単語の意味は？', code: 'esun',    answer: '市場・取引・売買',           dummies: ['家・建物',           'グループ・集団',       '道・方法'],              exp: '市場、商業、交換など取引に関するすべて。「esun e ijo」で「物を売買する」。' },
    { id: 'tp_ijo',     q: 'この単語の意味は？', code: 'ijo',     answer: 'もの・物体・何か',           dummies: ['人・誰か',           '動物・生き物',         '場所・土地'],            exp: 'あらゆる「もの」を指す最も汎用的な名詞。特定の単語がないものは ijo で表せる。' },
    { id: 'tp_ike',     q: 'この単語の意味は？', code: 'ike',     answer: '悪い・複雑・不要な',         dummies: ['良い・シンプル',     '強い・力強い',         '奇妙な・変な'],          exp: 'pona（良い）の反対語。トキポナでは「悪い」と「複雑」が同じ単語なのが哲学的特徴。' },
    { id: 'tp_ilo',     q: 'この単語の意味は？', code: 'ilo',     answer: '道具・機械・器具',           dummies: ['武器・戦い',         '食べ物・食料',         '布・衣服'],              exp: 'あらゆる道具・機械・楽器。「ilo musi」で楽器、「ilo toki」で電話などコミュニケーション機器を表せる。' },
    { id: 'tp_insa',    q: 'この単語の意味は？', code: 'insa',    answer: '内側・中心・胃',             dummies: ['外側・皮膚・境界',   '上・高い',             '横・近く'],              exp: '物理的な内部と比喩的な中心の両方。「insa mi」で「私の内側・私の胃」。' },
    { id: 'tp_jaki',    q: 'この単語の意味は？', code: 'jaki',    answer: '不潔・汚い・吐き気がする',   dummies: ['甘い・かわいい',     '良い・清潔',           '冷たい・涼しい'],        exp: '物理的な汚れも、不快感・不道徳さも表せる。「jaki ala」で「清潔・不快でない」。' },
    { id: 'tp_jan',     q: 'この単語の意味は？', code: 'jan',     answer: '人・誰か・人間',             dummies: ['動物・生き物',       '神・霊・超自然',       '場所・土地'],            exp: '人間全般を指す。名前の前に「jan」を付けて「jan Sonja（ソーニャさん）」のように使う。' },
    { id: 'tp_jelo',    q: 'この単語の意味は？', code: 'jelo',    answer: '黄色・黄色い',               dummies: ['赤・赤い',           '青・緑',               '白・明るい色'],          exp: 'オレンジ系の色も含む黄色。「jelo walo」で「クリーム色」など組み合わせで細かい色を表現できる。' },
    { id: 'tp_jo',      q: 'この単語の意味は？', code: 'jo',      answer: '持つ・所有する・含む',       dummies: ['与える・送る',       '使う・利用する',       '欲しい・必要とする'],    exp: '所有・携帯・含有のすべて。「mi jo e telo」で「私は水を持っている」。' },
    { id: 'tp_kala',    q: 'この単語の意味は？', code: 'kala',    answer: '魚・水生生物',               dummies: ['鳥・飛ぶ動物',       '虫・昆虫',             '爬虫類・両生類'],        exp: '魚・クジラ・タコなど水中の生き物全般。動物カテゴリ：soweli（陸）kala（水）waso（空）pipi（虫）akesi（爬虫類）。' },
    { id: 'tp_kalama',  q: 'この単語の意味は？', code: 'kalama',  answer: '音・鳴らす・声',             dummies: ['見る・目・視覚',     '匂う・鼻・嗅覚',       '感じる・触る・触覚'],    exp: 'あらゆる音・音声。「kalama musi」で音楽、「kalama ike」で騒音・不快な音。' },
    { id: 'tp_kama',    q: 'この単語の意味は？', code: 'kama',    answer: '来る・到着する・〜になる',   dummies: ['去る・離れる',       '待つ・止まる',         '戻る・繰り返す'],        exp: '補助動詞として「kama sona」で「学ぶ（知識になっていく）」。挨拶「kama pona！」は「よく来た！」の意味。' },
    { id: 'tp_kasi',    q: 'この単語の意味は？', code: 'kasi',    answer: '植物・草・木・葉',           dummies: ['動物・生き物',       '土・地面・大地',       '水・液体'],              exp: '草・木・花・苔など植物全般。「kasi suli」で大きな木、「kasi lili」で小草。' },
    { id: 'tp_ken',     q: 'この単語の意味は？', code: 'ken',     answer: 'できる・可能・許可',         dummies: ['しなければならない', 'したい・欲しい',       'している最中'],          exp: '能力・可能性・許可の三つを表す。「sina ken toki」で「あなたは話せる（話していい）」。' },
    { id: 'tp_kepeken', q: 'この単語の意味は？', code: 'kepeken', answer: '使う・〜を使って',           dummies: ['与える・送る',       '作る・組み立てる',     '壊す・分解する'],        exp: '道具や手段を使うことを表す。前置詞として「kepeken ilo」で「道具を使って」という意味になる。' },
    { id: 'tp_kili',    q: 'この単語の意味は？', code: 'kili',    answer: '果物・野菜・植物の実',       dummies: ['肉・動物の食べ物',   '穀物・パン・ご飯',     '飲み物・液体'],          exp: 'リンゴ・トマト・バナナなど植物由来の食べ物全般。「kili pona」で「おいしい果物」。' },
    { id: 'tp_kiwen',   q: 'この単語の意味は？', code: 'kiwen',   answer: '硬い・固体・石',             dummies: ['柔らかい・粘土状',   '液体・水',             '気体・空気'],            exp: '石・金属・骨など硬い物体。「kiwen loje」で赤い石＝ルビー的な表現もできる。' },
    { id: 'tp_ko',      q: 'この単語の意味は？', code: 'ko',      answer: '粉・泥・ペースト・柔らかい固体', dummies: ['石・硬い物',       '液体・水',             '気体・空気'],            exp: '小麦粉・泥・ペーストなど固体でも液体でもない中間の物質。' },
    { id: 'tp_kon',     q: 'この単語の意味は？', code: 'kon',     answer: '空気・精神・魂・見えない力', dummies: ['水・液体',           '土・地面',             '火・熱'],                exp: '物理的な空気と、精神・魂などの非物質的な「気」も表す。「kon pona」で「良い精神・良い雰囲気」。' },
    { id: 'tp_kule',    q: 'この単語の意味は？', code: 'kule',    answer: '色・カラフル',               dummies: ['形・形状',           '大きさ・サイズ',       '音・音声'],              exp: '色全般。「kule seme?」で「何色？」。具体的な色は loje（赤）laso（青緑）jelo（黄）walo（白）pimeja（黒）。' },
    { id: 'tp_kulupu',  q: 'この単語の意味は？', code: 'kulupu',  answer: 'グループ・集団・コミュニティ', dummies: ['一人・個人',         '家・建物',             '敵・対立'],              exp: '家族・チーム・国民・クラスなどあらゆる集合体。「kulupu toki pona」でトキポナコミュニティ。' },
    { id: 'tp_kute',    q: 'この単語の意味は？', code: 'kute',    answer: '聞く・耳・従う',             dummies: ['見る・目・視覚',     '話す・口・言語',       '感じる・心・感情'],      exp: '音を聞くことと、命令に従うことの両方を表す。「kute e mi」で「私の言うことを聞いて」。' },
    { id: 'tp_la',      q: 'この単語の意味は？', code: 'la',      answer: '文脈マーカー（〜の状況で）', dummies: ['目的語マーカー',     '述語マーカー',         '主語をつなぐ接続詞'],    exp: '前の節を文脈として後ろにつなぐ。「tenpo ni la」で「今この時に（は）」。if 節・時間・条件などを作る。' },
    { id: 'tp_lape',    q: 'この単語の意味は？', code: 'lape',    answer: '眠る・休む・非活動',         dummies: ['働く・作る・活動',   '動く・移動する',       '食べる・栄養を取る'],    exp: '睡眠・休息・不活性状態。「lape pona」で「よく眠ってね（おやすみなさい）」。' },
    { id: 'tp_laso',    q: 'この単語の意味は？', code: 'laso',    answer: '青・緑',                     dummies: ['赤・赤い',           '黄色・黄色い',         '白・明るい色'],          exp: '青と緑を一つの単語で表す。空の色も草の色も laso。「laso pimeja」で濃い緑・濃い青。' },
    { id: 'tp_lawa',    q: 'この単語の意味は？', code: 'lawa',    answer: '頭・支配する・法則',         dummies: ['足・脚・下',         '手・腕・5',            '心・感情'],              exp: '体の「頭」と、組織のトップや規則を表す。「lawa jan」でリーダー・上司。' },
    { id: 'tp_len',     q: 'この単語の意味は？', code: 'len',     answer: '布・衣服・隠す・覆う',       dummies: ['食べ物・食料',       '道具・機械',           '容器・箱'],              exp: '衣服・布地・カーテンなど覆うもの全般。動詞として「隠す」の意味にもなる。' },
    { id: 'tp_lete',    q: 'この単語の意味は？', code: 'lete',    answer: '冷たい・涼しい・生の',       dummies: ['熱い・温かい・火',   '甘い・甘味がある',     '硬い・固い'],            exp: '低温・生食（調理していない）を表す。「moku lete」で「生の食べ物・冷たい食べ物」。' },
    { id: 'tp_li',      q: 'この単語の意味は？', code: 'li',      answer: '述語マーカー',               dummies: ['目的語マーカー',     '文脈マーカー',         '主語を並べる接続詞'],    exp: '主語と述語（動詞・形容詞）の間に置く。「soweli li moku」で「動物は食べる」。主語が「mi」か「sina」のときは省略。' },
    { id: 'tp_lili',    q: 'この単語の意味は？', code: 'lili',    answer: '小さい・少ない・若い',       dummies: ['大きい・重要な',     '多い・たくさん',       '強い・力強い'],          exp: 'suli（大きい）の反対語。「lili」だけで「少し・ちょっと」という副詞にもなる。' },
    { id: 'tp_linja',   q: 'この単語の意味は？', code: 'linja',   answer: '線・糸・縄・長く柔らかいもの', dummies: ['点・丸・球',         '面・平らなもの',       '穴・空洞'],              exp: '糸・ロープ・髪・川など「長くて柔らかいもの」全般。「linja lawa」で髪の毛。' },
    { id: 'tp_lipu',    q: 'この単語の意味は？', code: 'lipu',    answer: '平らなもの・紙・本・文書',   dummies: ['丸いもの・球',       '容器・くぼみ',         '棒・細長いもの'],        exp: '紙・本・ページ・カード・葉など平らで薄いもの。「lipu toki pona」でトキポナの本（pu）のこと。' },
    { id: 'tp_loje',    q: 'この単語の意味は？', code: 'loje',    answer: '赤・赤い',                   dummies: ['青・緑',             '黄色・黄色い',         '黒・暗い'],              exp: 'オレンジ寄りの赤も含む。「loje mun」で月が赤く見える満月・皆既月食の表現に使える。' },
    { id: 'tp_lon',     q: 'この単語の意味は？', code: 'lon',     answer: 'ある・存在する・本当の・〜に', dummies: ['ない・存在しない',   '動く・変化する',       '始まる・作られる'],      exp: '存在・真実・場所を表す多機能な単語。「lon」だけで「本当！その通り！」という相槌になる。' },
    { id: 'tp_luka',    q: 'この単語の意味は？', code: 'luka',    answer: '手・腕・5',                  dummies: ['足・脚・下・2',      '頭・上・支配',         '目・見る・前'],          exp: '手には指が5本あることから「5」の意味も持つ。「luka tu」で「5+2=7」。' },
    { id: 'tp_lukin',   q: 'この単語の意味は？', code: 'lukin',   answer: '見る・目・探す・〜しようとする', dummies: ['聞く・耳',          '話す・口',             '匂う・鼻'],              exp: '視覚全般。補助動詞として「lukin pali」で「働こうとする」。「lukin pona」で「見た目が良い・かっこいい」。' },
    { id: 'tp_lupa',    q: 'この単語の意味は？', code: 'lupa',    answer: '穴・扉・窓・開口部',         dummies: ['壁・表面・平ら',     '屋根・天井',           '床・底'],                exp: '穴・窓・ドア・鍵穴など「開いている部分」全般。「lupa tomo」で窓やドア。' },
    { id: 'tp_ma',      q: 'この単語の意味は？', code: 'ma',      answer: '土地・国・外・地面',         dummies: ['空・上',             '海・水域',             '建物・屋内'],            exp: '陸地・国・屋外全般。「ma tomo」で都市・町（家の土地）、「ma telo」で湿地・沼。' },
    { id: 'tp_mama',    q: 'この単語の意味は？', code: 'mama',    answer: '親・創造者・起源',           dummies: ['子供・後世',         '兄弟・姉妹',           '友人・仲間'],            exp: '父親・母親どちらも mama。また「創造者・起源」という比喩的な意味も。「mama sona」で師匠・先生。' },
    { id: 'tp_mani',    q: 'この単語の意味は？', code: 'mani',    answer: 'お金・財産・家畜',           dummies: ['食べ物・食料',       '道具・機械',           '衣服・布'],              exp: '貨幣・コイン・富・家畜（かつての財産）。「mani mute」でお金持ち。' },
    { id: 'tp_meli',    q: 'この単語の意味は？', code: 'meli',    answer: '女性・女・妻',               dummies: ['男性・男・夫',       '子供・若者',           '老人・年長者'],          exp: '生物学的・社会的な女性。「meli mi」で「私の妻」。' },
    { id: 'tp_mi',      q: 'この単語の意味は？', code: 'mi',      answer: '私・私たち',                 dummies: ['あなた・あなたたち', '彼・彼女・それ',       '誰か・ある人'],          exp: 'トキポナで最も基本的な人称代名詞。「mi」の後の li は省略する。「mi moku」で「私は食べる」。' },
    { id: 'tp_mije',    q: 'この単語の意味は？', code: 'mije',    answer: '男性・男・夫',               dummies: ['女性・女・妻',       '子供・若者',           '老人・年長者'],          exp: '生物学的・社会的な男性。「mije mi」で「私の夫」。meli（女性）と対になる。' },
    { id: 'tp_moku',    q: 'この単語の意味は？', code: 'moku',    answer: '食べ物・食べる・飲む',       dummies: ['眠る・休む',         '働く・作る',           '歩く・移動する'],        exp: '食べる行為も食べ物自体も表す。飲むことも moku。「moku pona」で「おいしい・いただきます」。' },
    { id: 'tp_moli',    q: 'この単語の意味は？', code: 'moli',    answer: '死・殺す・死んだ',           dummies: ['生きる・生命',       '眠る・休む',           '病気・体調不良'],        exp: '死・死亡・致死的。「moli ala」で不死・死なない。「kama moli」で「死にかけている」。' },
    { id: 'tp_monsi',   q: 'この単語の意味は？', code: 'monsi',   answer: '後ろ・背後・お尻',           dummies: ['前・顔・壁',         '上・高い',             '横・近く'],              exp: '後方・背中側・お尻など「背面」全般。「monsi tomo」で家の裏。' },
    { id: 'tp_mu',      q: 'この単語の意味は？', code: 'mu',      answer: '動物の鳴き声・動物語',       dummies: ['人間の言葉・会話',   '楽器の音楽',           '自然の音・風'],          exp: '犬の「ワン」猫の「ニャー」など動物の鳴き声全般。また意味不明・コミュニケーション不能を表すことも。' },
    { id: 'tp_mun',     q: 'この単語の意味は？', code: 'mun',     answer: '月・星・夜の天体',           dummies: ['太陽・光・昼',       '雲・霧・空気',         '火・熱・光'],            exp: '月・星・惑星など夜空の天体全般。「mun pona」でいい月夜。suno（太陽）と対になる。' },
    { id: 'tp_musi',    q: 'この単語の意味は？', code: 'musi',    answer: '楽しい・遊ぶ・芸術・ゲーム', dummies: ['悲しい・泣く',       '働く・真剣な',         '怖い・恐ろしい'],        exp: '楽しみ・娯楽・アート・ゲーム全般。「toki musi」で物語・フィクション。「musi pona」で楽しい時間を過ごしてね。' },
    { id: 'tp_mute',    q: 'この単語の意味は？', code: 'mute',    answer: '多い・たくさん・とても・20', dummies: ['少ない・小さい',     '一つ・唯一',           'ゼロ・なし'],            exp: 'lili（少ない）の反対語。数体系では「20」を意味する。「mute mute」で非常に多い・無数。' },
    { id: 'tp_nanpa',   q: 'この単語の意味は？', code: 'nanpa',   answer: '数・番号・〜番目',           dummies: ['名前・言葉',         '時間・状況',           '色・外見'],              exp: '序数を作るのにも使う。「nanpa wan」で「第一・1番目」。「nanpa pona」で「素晴らしい（文字通り「良い数字」）」という褒め言葉。' },
    { id: 'tp_nasa',    q: 'この単語の意味は？', code: 'nasa',    answer: '奇妙な・おかしい・酔った',   dummies: ['普通・正常・真面目', '良い・シンプル',       '悪い・複雑'],            exp: '変・ユニーク・風変わり・酔っている。「telo nasa」で「奇妙な液体＝お酒」。' },
    { id: 'tp_nasin',   q: 'この単語の意味は？', code: 'nasin',   answer: '道・方法・哲学・システム',   dummies: ['場所・位置',         '目的・ゴール',         '理由・原因'],            exp: '物理的な道路から、考え方・ライフスタイルまで表せる。「nasin toki pona」でトキポナの哲学・やり方。' },
    { id: 'tp_nena',    q: 'この単語の意味は？', code: 'nena',    answer: '鼻・丘・でっぱり・突起',     dummies: ['穴・くぼみ・扉',     '平らな場所・平地',     '口・開口部'],            exp: '顔の鼻も、山の丘も、物の突起も nena。「nena suli」で山・丘陵。' },
    { id: 'tp_ni',      q: 'この単語の意味は？', code: 'ni',      answer: 'これ・あれ・その',           dummies: ['何・どれ（疑問）',   '誰・どの人',           '全て・すべて'],          exp: '近いものも遠いものも ni で指せる。「ni li pona」で「これ・それは良い」。that節を作るのにも使う。' },
    { id: 'tp_nimi',    q: 'この単語の意味は？', code: 'nimi',    answer: '名前・言葉・単語',           dummies: ['数・番号',           '色・見た目',           '形・形状'],              exp: '名前・単語・言葉全般。「nimi mi li...」で「私の名前は...」。「nimi pona」で良い名前・美しい言葉。' },
    { id: 'tp_noka',    q: 'この単語の意味は？', code: 'noka',    answer: '足・脚・下・底',             dummies: ['手・腕・5',          '頭・上・支配',         '目・前・見る'],          exp: '足・脚・何かの下部・底。「noka tomo」で家の基礎・一階部分。' },
    { id: 'tp_o',       q: 'この単語の意味は？', code: 'o',       answer: '命令・呼びかけ・〜よ',       dummies: ['疑問文マーカー',     '感嘆詞・強調',         '過去を表すマーカー'],    exp: '命令文を作る（「o moku!」で「食べろ！」）か、呼びかけ（「jan Sonja o」でソーニャさんよ）を表す。' },
    { id: 'tp_olin',    q: 'この単語の意味は？', code: 'olin',    answer: '愛・愛する・大切にする',     dummies: ['嫌う・避ける',       '知る・学ぶ',           '遊ぶ・楽しむ'],          exp: '深い愛情・感情的な絆を表す最も純粋な「愛」の単語。「mi olin e sina」で「私はあなたを愛している」。' },
    { id: 'tp_ona',     q: 'この単語の意味は？', code: 'ona',     answer: '彼・彼女・それ・彼ら',       dummies: ['私・私たち',         'あなた・あなたたち',   '誰か・ある人'],          exp: '三人称の代名詞。性別・単数複数を区別しない。「ona li pona」で「彼/彼女/それは良い」。' },
    { id: 'tp_open',    q: 'この単語の意味は？', code: 'open',    answer: '開ける・始める・起動する',   dummies: ['閉める・終わる',     '壊す・分解する',       '保つ・続ける'],          exp: 'ドアを開ける・物語を始める・プログラムを起動するなど「開始」全般。「open toki」で話し始める。' },
    { id: 'tp_pakala',  q: 'この単語の意味は？', code: 'pakala',  answer: '壊れた・失敗・事故',         dummies: ['完璧・成功',         '作る・修理する',       '良い・きれい'],          exp: '壊れた状態・失敗・事故・ミス。「pakala!」で「くそ！やっちゃった！」という感嘆詞にもなる。' },
    { id: 'tp_pali',    q: 'この単語の意味は？', code: 'pali',    answer: '作る・働く・行動する',       dummies: ['壊す・削る',         '休む・眠る',           '遊ぶ・楽しむ'],          exp: '制作・労働・行動全般。「pali pona」で「良い仕事・良い作品」。lape（休む）と対になる。' },
    { id: 'tp_palisa',  q: 'この単語の意味は？', code: 'palisa',  answer: '棒・細長い固体・枝',         dummies: ['丸いもの・球',       '平らなもの・板',       '穴・容器'],              exp: '棒・枝・骨・鉛筆など「長くて硬いもの」。linja（線・糸）は柔らかいが palisa は硬い。' },
    { id: 'tp_pan',     q: 'この単語の意味は？', code: 'pan',     answer: '穀物・パン・ご飯・粉物',     dummies: ['果物・野菜',         '肉・動物性食品',       '飲み物・液体'],          exp: '米・小麦・パン・麺など穀物由来の食べ物全般。「pan pona」でおいしいご飯・おいしいパン。' },
    { id: 'tp_pana',    q: 'この単語の意味は？', code: 'pana',    answer: '与える・送る・放出する',     dummies: ['受け取る・もらう',   '持つ・所有する',       '使う・消費する'],        exp: '贈る・送信・発射・放出など「外に向かう動き」全般。「pana e sona」で知識を教える・情報を共有する。' },
    { id: 'tp_pi',      q: 'この単語の意味は？', code: 'pi',      answer: '〜の（グループを再分割）',   dummies: ['〜から・理由',       '〜を使って・手段',     '〜と一緒に'],            exp: '複数の修飾語をグループ化する。「tomo telo nasa」は「変な水の家」だが「tomo pi telo nasa」は「お酒の家（バー）」。' },
    { id: 'tp_pilin',   q: 'この単語の意味は？', code: 'pilin',   answer: '感じる・心・感情・触れる',   dummies: ['考える・脳・理性',   '話す・声・意見',       '見る・目・観察'],        exp: '感情・直感・触覚・心の状態。「pilin pona」で気分が良い、「pilin ike」で気分が悪い・辛い。' },
    { id: 'tp_pimeja',  q: 'この単語の意味は？', code: 'pimeja',  answer: '黒・暗い・影',               dummies: ['白・明るい・輝く',   '赤・赤い',             '青・緑'],                exp: 'walo（白）の反対語。「tenpo pimeja」で「暗い時間＝夜」。「pimeja mute」で非常に暗い。' },
    { id: 'tp_pini',    q: 'この単語の意味は？', code: 'pini',    answer: '終わり・止まる・完了・過去', dummies: ['始まり・開ける・未来', '続ける・保つ・現在',  '待つ・準備中'],          exp: '完了・終了・過去を表す。「pini la」で「以前・昔は」。「tenpo pini」で過去の時間。' },
    { id: 'tp_pipi',    q: 'この単語の意味は？', code: 'pipi',    answer: '虫・昆虫・小さい動物',       dummies: ['魚・水生生物',       '鳥・飛ぶ動物',         '爬虫類・両生類'],        exp: '昆虫・クモ・ムカデなど小さい節足動物全般。「pipi lili」でアリなど極小の虫。' },
    { id: 'tp_poka',    q: 'この単語の意味は？', code: 'poka',    answer: '横・側面・近く・一緒に',     dummies: ['上・遠い・高い',     '下・低い',             '前・正面'],              exp: '隣・側面・近接・そばにいること。「poka mi」で私の隣・私のそばに。「lon poka」で〜のそばで。' },
    { id: 'tp_poki',    q: 'この単語の意味は？', code: 'poki',    answer: '容器・箱・カップ・入れ物',   dummies: ['平らなもの・紙',     '棒・細長いもの',       '丸い固体・球'],          exp: 'カップ・箱・袋・容器など中に何かを入れるもの全般。「poki telo」でコップ・水筒。' },
    { id: 'tp_pona',    q: 'この単語の意味は？', code: 'pona',    answer: '良い・シンプル・修理する',   dummies: ['悪い・複雑',         '大きい・重要な',       '奇妙な・変な'],          exp: 'トキポナで最も重要な単語。「良い」「シンプル」「修理する」を全て表す。言語名「toki pona」は「良い言語」の意味。' },
    { id: 'tp_pu',      q: 'この単語の意味は？', code: 'pu',      answer: 'トキポナ公式本・本に従って交流する', dummies: ['インターネット・SNS', '音楽・アート作品', '食べ物・料理'],          exp: '2014年に出版されたトキポナ公式本（Toki Pona: The Language of Good）のこと。また、その本に従う・その本を読む行為を表す動詞でもある。' },
    { id: 'tp_sama',    q: 'この単語の意味は？', code: 'sama',    answer: '同じ・似ている・同士',       dummies: ['異なる・別の',       '反対・逆',             '新しい・追加の'],        exp: '同一性・類似性を表す。前置詞として「sama mi」で「私と同じように」。「sama sama」でまったく同一。' },
    { id: 'tp_seli',    q: 'この単語の意味は？', code: 'seli',    answer: '火・熱い・温かい・料理する', dummies: ['水・液体',           '冷たい・涼しい',       '土・地面'],              exp: 'lete（冷たい）の反対語。「seli moku」で食べ物を温める・料理する。「seli suno」で太陽熱。' },
    { id: 'tp_selo',    q: 'この単語の意味は？', code: 'selo',    answer: '外側・皮膚・皮・境界',       dummies: ['内側・中心・胃',     '全体・中身',           '上・表面の下'],          exp: '表皮・樹皮・境界・外壁など「外側を覆うもの」全般。insa（内側）と対になる。' },
    { id: 'tp_seme',    q: 'この単語の意味は？', code: 'seme',    answer: '何・どれ・どの（疑問詞）',   dummies: ['これ・あれ・それ',   '全て・すべて',         'なし・ゼロ'],            exp: 'トキポナ唯一の疑問詞。「seme」を知りたい部分に置く。「sina pali e seme?」で「あなたは何を作っているの？」' },
    { id: 'tp_sewi',    q: 'この単語の意味は？', code: 'sewi',    answer: '上・高い・神聖な・空・神',   dummies: ['下・低い・服従する', '横・平ら',             '前・正面・顔'],          exp: '物理的な「上」と、精神的な「神聖・崇高」の両方。「sewi」だけで神・天・空を指すことも。anpa（下）と対。' },
    { id: 'tp_sijelo',  q: 'この単語の意味は？', code: 'sijelo',  answer: '体・物理的状態・形態',       dummies: ['心・精神・感情',     '名前・アイデンティティ', '影・形・外見'],          exp: '生物の身体・体の健康状態。「sijelo pona」で体が良い＝健康。「sijelo ike」で体調不良・病気。' },
    { id: 'tp_sike',    q: 'この単語の意味は？', code: 'sike',    answer: '円・球・丸・繰り返す',       dummies: ['四角・箱・直方体',   '三角・角',             '線・直線'],              exp: '丸い形状と、循環・繰り返しを表す。「sike suno」で太陽の周り＝1年。「tenpo sike」で年・サイクル。' },
    { id: 'tp_sin',     q: 'この単語の意味は？', code: 'sin',     answer: '新しい・追加の・もう一つ',   dummies: ['古い・以前の',       '同じ・変化なし',       '少ない・減る'],          exp: '新鮮・新規・追加。「sin la」で「さらに・また加えて」。「ijo sin」で新しいもの・ニュース。' },
    { id: 'tp_sina',    q: 'この単語の意味は？', code: 'sina',    answer: 'あなた・あなたたち',         dummies: ['私・私たち',         '彼・彼女・それ',       '誰か・ある人'],          exp: '二人称の代名詞。単数も複数も同じ。「sina」の後の li は省略する。「toki sina」で「やあ！」。' },
    { id: 'tp_sinpin',  q: 'この単語の意味は？', code: 'sinpin',  answer: '前・顔・壁・正面',           dummies: ['後ろ・背後・お尻',   '上・天井',             '横・側面'],              exp: '正面・顔・壁・フロント全般。「sinpin tomo」で家の正面・玄関側の壁。monsi（後ろ）と対。' },
    { id: 'tp_sitelen', q: 'この単語の意味は？', code: 'sitelen', answer: '描く・画像・文字・シンボル', dummies: ['音・声・音楽',       '香り・匂い',           '感触・手触り'],          exp: '絵・写真・文字・象形文字・映像など視覚的なシンボル全般。「sitelen pona」はトキポナの象形文字の名前でもある。' },
    { id: 'tp_sona',    q: 'この単語の意味は？', code: 'sona',    answer: '知る・知識・スキル・情報',   dummies: ['知らない・忘れる',   '感じる・感情',         '信じる・思う'],          exp: '「sona pona」で知恵・良い知識。「mi sona ala」で「わからない」。補助動詞「sona pali」で工作できる。' },
    { id: 'tp_soweli',  q: 'この単語の意味は？', code: 'soweli',  answer: '陸の動物・毛のある動物',     dummies: ['海の生き物・魚',     '空を飛ぶ動物・鳥',     '虫・昆虫'],              exp: '犬・猫・象・うさぎなど陸生哺乳類。「soweli pona」で「良い動物・いい子」（ペットへの呼びかけ）。' },
    { id: 'tp_suli',    q: 'この単語の意味は？', code: 'suli',    answer: '大きい・重要な・成長した',   dummies: ['小さい・少ない',     '速い・軽い',           '普通・中間'],            exp: 'lili（小さい）の反対語。物理的な大きさと、重要性・深刻さの両方を表す便利な単語。' },
    { id: 'tp_suno',    q: 'この単語の意味は？', code: 'suno',    answer: '太陽・光・明るい・輝く',     dummies: ['月・星・夜の天体',   '雲・霧',               '夜・暗さ'],              exp: 'mun（月）と対になる太陽の単語。「tenpo suno」で昼・一日。「suno pona」でおはよう（良い光・良い昼）。' },
    { id: 'tp_supa',    q: 'この単語の意味は？', code: 'supa',    answer: '平らな表面・テーブル・床・棚', dummies: ['丸いもの・球',       '容器・くぼみ',         '棒・細長いもの'],        exp: 'テーブル・床・棚・ベッドなど「平らで上に物を置ける面」。「supa lape」でベッド（眠る平面）。' },
    { id: 'tp_suwi',    q: 'この単語の意味は？', code: 'suwi',    answer: '甘い・かわいい・美味しい',   dummies: ['辛い・苦い',         '醜い・不快な',         '硬い・冷たい'],          exp: '味の甘さと、見た目のかわいらしさの両方。「jan suwi」で「かわいい人・甘い人」。' },
    { id: 'tp_tan',     q: 'この単語の意味は？', code: 'tan',     answer: '〜から・原因・理由',         dummies: ['〜へ・目的地',       '〜と一緒に',           '〜のために'],            exp: '出発点・原因・理由を表す前置詞。「tan seme?」で「なぜ？（何から？）」。tawa（〜へ）と対。' },
    { id: 'tp_taso',    q: 'この単語の意味は？', code: 'taso',    answer: 'だけ・しかし・ただ',         dummies: ['全て・すべて',       'または・選択',         'そして・さらに'],        exp: '「〜だけ」という制限と、「しかし」という逆接の両方を表す。「mi taso」で「私だけ」。文頭で「しかし」。' },
    { id: 'tp_tawa',    q: 'この単語の意味は？', code: 'tawa',    answer: '動く・〜へ・〜のために',     dummies: ['止まる・〜から',     '待つ・留まる',         '横・近く'],              exp: '移動・目的地・受益者を示す。「tawa pona！」で「良い旅を！さようなら！」。tan（〜から）と対。' },
    { id: 'tp_telo',    q: 'この単語の意味は？', code: 'telo',    answer: '水・液体・飲み物',           dummies: ['火・熱い',           '空気・風',             '土・地面'],              exp: 'あらゆる液体。「telo nasa」でお酒（奇妙な液体）。「telo seli」でお湯・温かい飲み物。' },
    { id: 'tp_tenpo',   q: 'この単語の意味は？', code: 'tenpo',   answer: '時間・状況・場合',           dummies: ['場所・位置',         '人・存在',             '数・量'],                exp: '時間・時代・タイミング全般。「tenpo ni」で「今・現在」。「tenpo seme?」で「いつ？」' },
    { id: 'tp_toki',    q: 'この単語の意味は？', code: 'toki',    answer: '言語・話す・コミュニケーション', dummies: ['聞く・耳',          '見る・目',             '書く・描く'],            exp: 'トキポナ最初に覚える単語。「toki!」だけで「やあ！こんにちは！」の挨拶。「toki pona」で「良い言語」。' },
    { id: 'tp_tomo',    q: 'この単語の意味は？', code: 'tomo',    answer: '家・建物・部屋・室内',       dummies: ['土地・野外',         '乗り物・移動手段',     '道・方法'],              exp: '「tomo telo」でお風呂・トイレ（水の部屋）。「tomo moku」でキッチン・レストラン。「tomo toki」で電話・通信室。' },
    { id: 'tp_tu',      q: 'この単語の意味は？', code: 'tu',      answer: '2・分ける・ペア',            dummies: ['1・唯一・合わせる',  '5・手',                '多い・たくさん'],        exp: '数の「2」と「分割する」の両方。「tu tu」で4。「luka tu」で7。wan（1）、luka（5）と合わせて数を作る。' },
    { id: 'tp_unpa',    q: 'この単語の意味は？', code: 'unpa',    answer: '性的な関係・セックス',       dummies: ['戦う・競争する',     '食べる・食事する',     '踊る・体を動かす'],      exp: '性的な関係・セックスを表す。トキポナでは禁句なく直接的に表現する。' },
    { id: 'tp_uta',     q: 'この単語の意味は？', code: 'uta',     answer: '口・唇・くちばし',           dummies: ['目・見る',           '耳・聞く',             '鼻・匂う'],              exp: '口・唇・くちばしなど口に当たる部分。「uta moku」で食べ物を口に入れる・口で食べる。' },
    { id: 'tp_utala',   q: 'この単語の意味は？', code: 'utala',   answer: '戦う・競争する・挑戦',       dummies: ['仲良くする・平和',   '休む・眠る',           '遊ぶ・楽しむ'],          exp: '戦争・スポーツ・議論など競争・対立全般。「utala pona」でスポーツマンシップ・良い競争。' },
    { id: 'tp_walo',    q: 'この単語の意味は？', code: 'walo',    answer: '白・明るい・淡い色',         dummies: ['黒・暗い',           '赤・赤い',             '青・緑'],                exp: 'pimeja（黒）の反対語。純白だけでなく、淡いクリーム・ベージュも walo。「walo seli」でオレンジ・暖色。' },
    { id: 'tp_wan',     q: 'この単語の意味は？', code: 'wan',     answer: '1・唯一の・合わせる',        dummies: ['2・分ける',          '5・手・腕',            '多い・たくさん'],        exp: '数の「1」、「唯一の」、そして「合体させる」の意味も。「wan taso」で「たった一つだけ」。tu（2）と対。' },
    { id: 'tp_waso',    q: 'この単語の意味は？', code: 'waso',    answer: '鳥・飛ぶ動物',               dummies: ['魚・水生生物',       '虫・昆虫',             '爬虫類・両生類'],        exp: '鳥・コウモリ・飛行機など空を飛ぶもの全般（比喩的に）。「waso suli」でタカ・ワシなど大型の鳥。' },
    { id: 'tp_wawa',    q: 'この単語の意味は？', code: 'wawa',    answer: '強い・力・エネルギー',       dummies: ['弱い・力がない',     '静か・穏やか',         '普通・中程度'],          exp: '物理的な強さ・電気・精神的なパワー全般。「wawa!」だけで「すごい！」という感嘆表現になる。' },
    { id: 'tp_weka',    q: 'この単語の意味は？', code: 'weka',    answer: '離れた・消す・遠ざける',     dummies: ['近い・隣にある',     '来る・到着する',       '保つ・残す'],            exp: '遠い・不在・除去。「weka e ijo ike」で「悪いものを取り除く」。「mi weka」で「私はいない・私は去る」。' },
    { id: 'tp_wile',    q: 'この単語の意味は？', code: 'wile',    answer: '欲しい・必要・〜したい',     dummies: ['持っている・所有',   'できる・可能・許可',   '嫌い・不要'],            exp: '欲望と義務の両方を表す。「mi wile moku」で「食べたい」。「wile ala」で「〜したくない・不要」。' },
  ],

};
